// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuqcz3EeXS_yUn4ehzTTbCzwzFgZKkcbA',
    appId: '1:180184763981:android:48dc1f4f1a7c018dced604',
    messagingSenderId: '180184763981',
    projectId: 'doctor-appointment-app-pro',
    storageBucket: 'doctor-appointment-app-pro.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2EsGTlvGUvEX3_8Kry5cQHZKI2DOmisI',
    appId: '1:180184763981:web:1d7e7453574a34c3ced604',
    messagingSenderId: '180184763981',
    projectId: 'doctor-appointment-app-pro',
    authDomain: 'doctor-appointment-app-pro.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-pro.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADC8Vr-luIhnxCM9-SVxkhq5ykkmZLzko',
    appId: '1:180184763981:ios:d0d055035febaabfced604',
    messagingSenderId: '180184763981',
    projectId: 'doctor-appointment-app-pro',
    storageBucket: 'doctor-appointment-app-pro.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentAppFrontDefinitivoFront',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADC8Vr-luIhnxCM9-SVxkhq5ykkmZLzko',
    appId: '1:180184763981:ios:d0d055035febaabfced604',
    messagingSenderId: '180184763981',
    projectId: 'doctor-appointment-app-pro',
    storageBucket: 'doctor-appointment-app-pro.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentAppFrontDefinitivoFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2EsGTlvGUvEX3_8Kry5cQHZKI2DOmisI',
    appId: '1:180184763981:web:b1fc607a5261cf1bced604',
    messagingSenderId: '180184763981',
    projectId: 'doctor-appointment-app-pro',
    authDomain: 'doctor-appointment-app-pro.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-pro.firebasestorage.app',
  );

}